version: '3.3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8000:8080
    volumes:
      - ./app/swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      URL: /swagger.yml # default

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 8002:8080
