version: '3.3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8000:8080
    volumes:
      - ./app/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      URL: /openapi.yml # default

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 8001:8080
